positive_emoji: "triangle_heart"
heart_path: "assets/success.png"

commands:

  help:
    aliases:
      - help
      - please
    bot_permissions:
      guild: []
      channel:
        - read_messages
        - send_messages
    user_permissions:
      guild: []
      channel: []

  add_positive_emoji:
    aliases:
      - add-positive-emoji
      - add-heart
      - heart
    bot_permissions:
      guild:
        - manage_emojis
      channel: []
    user_permissions:
      guild:
        - manage_emojis
      channel: []